"""Node — validate_output

Validates every generated section against its template block kind:
- process_map blocks must be valid `flowchart TD` Mermaid
- table blocks must be valid markdown pipe tables
- all sections are capped at 2 000 characters
- missing keys are filled with a Gap placeholder

Always applies safe-fallback repairs so persist_output can ship something
even at MAX_RETRIES. Additionally emits `validation_errors` (one-sentence
constraint hints) for any section that needed non-trivial repair —
non-empty + retry budget left routes back to generate_sections.
"""
from __future__ import annotations

import logging

from video_add_agent.models.input import ActiveAddTemplate
from video_add_agent.models.template import BlockKind, TemplateDefinition
from video_add_agent.nodes.generate_sections import _make_fallback_blocks
from video_add_agent.state import ErrorInfo, VideoAgentState
from video_add_agent.utils.markdown import (
    enforce_section_cap,
    fix_mermaid,
    validate_mermaid,
    validate_pipe_table,
)

logger = logging.getLogger(__name__)

_MAX_SECTION_CHARS = 2_000
_GAP = "> **Gap:** To be confirmed with SME"
_MERMAID_PLACEHOLDER = "```mermaid\nflowchart TD\n  A[\"To be confirmed with SME\"]\n```"


def validate_output_node(state: VideoAgentState) -> dict:
    logger.info("validate_output: start project_id=%s", state.project_id)
    try:
        sections: dict[str, str] = dict(state.sections)
        template = ActiveAddTemplate.model_validate(state.active_add_template)

        try:
            tmpl_def = TemplateDefinition.model_validate_json(template.definition)
            all_blocks = tmpl_def.all_blocks()
        except Exception:
            all_blocks = _make_fallback_blocks()

        # Only validate dynamic blocks that have an outputKey. Static blocks
        # are emitted verbatim at stitch time, not generated by the LLM.
        dynamic_blocks = [
            (s, b) for s, b in all_blocks
            if b.kind is not BlockKind.static and b.outputKey
        ]
        block_kinds = {b.outputKey: b.kind.normalized for _, b in dynamic_blocks}
        expected_keys = [b.outputKey for _, b in dynamic_blocks]
        validation_errors: list[str] = []

        # Fill missing keys with Gap; flag as constraint
        for key in expected_keys:
            if key not in sections:
                sections[key] = _GAP
                validation_errors.append(
                    f"Section '{key}' was missing from generated output — must be present."
                )
                logger.warning("validate_output: missing key %s — filled with gap", key)

        # Per-kind repair + constraint emission. `kind` here is already
        # normalized to one of the canonical generator categories.
        for key, kind in block_kinds.items():
            content = sections.get(key, "")
            if not content:
                continue

            if kind == BlockKind.process_map:
                fixed = fix_mermaid(content)
                if not validate_mermaid(fixed):
                    sections[key] = _MERMAID_PLACEHOLDER
                    validation_errors.append(
                        f"Section '{key}' must contain a valid Mermaid `flowchart TD` block "
                        f"(no image:// URLs, no emoji in labels, fenced as ```mermaid)."
                    )
                    logger.warning("validate_output: %s mermaid invalid — replaced", key)
                else:
                    sections[key] = fixed

            elif kind == BlockKind.table:
                if not validate_pipe_table(content):
                    sections[key] = content + f"\n\n{_GAP}"
                    validation_errors.append(
                        f"Section '{key}' must be a valid markdown pipe table "
                        f"(header row, `|---|` separator, data rows)."
                    )
                    logger.warning("validate_output: %s table malformed — gap appended", key)

            sections[key] = enforce_section_cap(sections[key], _MAX_SECTION_CHARS)

        logger.info(
            "validate_output: %d sections checked, %d constraint hint(s) emitted",
            len(sections), len(validation_errors),
        )
        result: dict = {"sections": sections, "validation_errors": validation_errors}
        if validation_errors:
            new_counts = dict(state.retry_counts)
            new_counts["generate_sections"] = (
                new_counts.get("generate_sections", 0) + 1
            )
            result["retry_counts"] = new_counts
        return result

    except Exception as exc:
        logger.error("validate_output: failed — %s", exc, exc_info=True)
        return {"error": ErrorInfo(message=str(exc), failed_node="validate_output")}
